- .github/workflows/unittest.yml
> Feature(MInference): fix unittest

- README.md
> Feature(MInference): add arXiv paper

- .github/workflows/release.yml
- .github/workflows/scripts/build.sh
- .github/workflows/unittest.yml
- .gitignore
- README.md
- minference/version.py
- setup.py
- fix the pip setup issue;
- update the pdf link;
- fix the unittest pipeline;
> Hotfix(MInference): fix the pip setup issue

- .github/workflows/release.yml
- .github/workflows/scripts/build.sh
- .github/workflows/scripts/pytorch-install.sh
- MANIFEST.in
- README.md
- minference/version.py
- setup.py
- fix the pip setup;
- update paper information;
> Hotfix(MInference): fix the pip setup

- .github/workflows/release.yml
> Hotfix(MInference): fix the yaml

- MANIFEST.in
- README.md
- minference/modules/minference_forward.py
- fix the configs in pip;
- add vllm warning;
> Hotfix(MInference): fix the configs in pip

- minference/version.py
> Prerelease(MInference): update version

- README.md
- update HF demo information, thanks @AK's sponsoring;
> Feature(MInference): update HF demo information, thanks @AK's sponsoring

- Makefile
- experiments/benchmarks/benchmark_e2e.py
- tests/test_e2e.py
> Feature(MInference): add unittest

- minference/version.py
Prerelease for 0.1.4.post2
@iofu728
> Prerelease(MInference): for 0.1.4.post2

- README.md
- experiments/README.md
- experiments/benchmarks/benchmark_e2e.py
- experiments/benchmarks/benchmark_e2e_vllm.py
- experiments/benchmarks/run_e2e_vllm.sh
- Add e2e benchmark using vllm;
@iofu728
> Feature(MInference): add e2e benchmark using vllm

- experiments/README.md
- experiments/infinite_bench/run_infinitebench.py
- minference/ops/streaming_kernel.py
- Fixes e2e benchmark guideline #65;
- Fixed A-shape multi-gpu support;
@iofu728
> Fix(MInference): fix e2e benchmark guideline & fix A-shape multi gpu

- minference/modules/minference_forward.py
- minference/patch.py
- minference/version.py
- Fixes vs pattern loss / sqrt(dk); #69 
@iofu728
> Fix(MInference): fix the vs pattern loss / sqrt(dk)

- README.md
- Add RetrievalAttention news;
- Add NeurIPS'24 result;
> Feature(MInference): update NeurIPS results

- README.md
- experiments/benchmarks/benchmark_e2e.py
- experiments/benchmarks/benchmark_e2e_vllm.py
- experiments/benchmarks/benchmark_e2e_vllm_tp.py
- experiments/infinite_bench/args.py
- experiments/infinite_bench/run_infinitebench.py
- experiments/needle_in_a_haystack/needle_test.py
- experiments/needle_in_a_haystack/needle_tools.py
- experiments/ppl/run_ppl.py
- experiments/ruler/pred/call_api.py
- minference/minference_configuration.py
- minference/models_patch.py
- minference/modules/flexprefill.py
- minference/modules/forward.py
- minference/modules/minference_forward.py
- scbench/args.py
- scbench/run_scbench.py
> Feature(FlexPrefill): add flex-prefill

- README.md
- scbench/args.py
- scbench/scripts/run_all_tasks.sh
- Fixes default seq_length in SCBench;
@iofu728
> Fix(SCBench): fix default seq length

- README.md
- minference/version.py
- scbench/readme.md
- scbench/scripts/run_all_tasks.sh
- scbench/scripts/run_single_method.sh
- Rewrite the SCBench scripts;
@iofu728
> Feature(SCBench): update scbench scripts

- minference/modules/forward.py
- minference/patch.py
- bug fix when `use_cache == False`
@iofu728
> Fix(SCBench): bug fix when `use_cache == False`

- .pre-commit-config.yaml
- README.md
- assets/license_header.txt
- examples/run_hf_streaming.py
- minference/modules/forward.py
- minference/modules/kivi.py
- minference/modules/kvcompression.py
- minference/modules/minference_forward.py
- minference/modules/quest.py
- minference/modules/retr_attn.py
- minference/ops/streaming_kernel.py
- minference/patch.py
- minference/utils.py
- minference/version.py
- Fixes #112, import issue due to transformers >= 4.48.0;
- Add ICLR'25 result;
@iofu728
> Feature(MInference): support transformers>=4.48.0 and add ICLR'25 result

- README.md
> Feature(MInference): add Qwen-Turbo-1M

- README.md
> Feature(SCBench): update bibtex

- README.md
> Feature(MInference): add Qwen2.5-1M

- .pre-commit-config.yaml
- minference/modules/flexprefill.py
- minference/modules/minference_forward.py
- minference/modules/retr_attn.py
- setup.py
Fixes #119, fix get config
@iofu728
> Fix(MInference): fix get config

- minference/configs/model2path.py
correct qwen2.5 config file name
> Fix the Qwen config path in model2path.py

- README.md
- examples/run_hf.py
- examples/run_hf_streaming.py
- experiments/benchmarks/benchmark_e2e.py
- experiments/infinite_bench/run_infinitebench.py
- experiments/needle_in_a_haystack/needle_tools.py
- experiments/ruler/pred/model_wrappers.py
- minference/patch.py
- tests/test_e2e.py
- Support chunk MLP;
- Support transformers >= 4.46.0;
- Add `kv_type` quick start;
- Add OOM FAQ;
@iofu728
> Feature(MInference): support transformers>=4.46.0, add chunk mlp

- .github/workflows/release.yml
- .github/workflows/scripts/pytorch-install.sh
- update release cuda version;
@iofu728
> Feature(MInference): update release cuda version

- README.md
- Update MMInference has been accepted by ICML'25
@iofu728
> Feature(MMInference): MMInference has been accepted by ICML'25

- .github/workflows/release.yml
- fix the release dependency
@iofu728
> Fix(MInference): fix the release dependency

- .github/workflows/release.yml
- fix release torch version
@iofu728
> Fixed(MInference): fix the release torch version

- .github/workflows/release.yml
Fix the release build
@iofu728
> Fix(MInference): fix the release build

- README.md
- experiments/benchmarks/benchmark_e2e.py
- minference/modules/forward.py
- minference/patch.py
- minference/utils.py
- scbench/eval_utils.py
- tests/test_e2e.py
> Fix(MInference): fix logits_to_keep

- TriangleMix/README.md
- TriangleMix/ruler/config_models.sh
- TriangleMix/ruler/config_tasks.sh
- TriangleMix/ruler/data/prepare.py
- TriangleMix/ruler/data/synthetic/common_words_extraction.py
- TriangleMix/ruler/data/synthetic/constants.py
- TriangleMix/ruler/data/synthetic/freq_words_extraction.py
- TriangleMix/ruler/data/synthetic/json/download_paulgraham_essay.py
- TriangleMix/ruler/data/synthetic/json/download_qa_dataset.sh
- TriangleMix/ruler/data/synthetic/niah.py
- TriangleMix/ruler/data/synthetic/qa.py
- TriangleMix/ruler/data/synthetic/variable_tracking.py
- TriangleMix/ruler/data/template.py
- TriangleMix/ruler/data/tokenizer.py
- TriangleMix/ruler/eval/evaluate.py
- TriangleMix/ruler/eval/synthetic/constants.py
- TriangleMix/ruler/pred/call_api.py
- TriangleMix/ruler/pred/client_wrappers.py
- TriangleMix/ruler/pred/serve_trt.py
- TriangleMix/ruler/pred/serve_vllm.py
- TriangleMix/speed_test.py
- minference/modules/tri_mix.py
Fix precommit issue in previous TriangleMix commit.
> Fix precommit issue in triangle mix
